### ISSUE TITLE
Please keep the generated information in the saved images

### ISSUE THREAD

**Issue by aylz10** [jordenyt/stable_diffusion_sketch#13]
During the use process, it was found that there was no generated information in the saved image exif, making it inconvenient to regenerate or redraw the image in the future.Please keep the generated information in the saved images.

The above content is translated using translation software

**Comment by jordenyt** [comment]
It is what I am planning to do in the next version. Stay tuned.

**Comment by aylz10** [comment]
Thank you for your reply. I also found an issue where the cfg setting in img2img does not work. Looking forward to the next version

The above content is translated using translation software

**Comment by jordenyt** [comment]
Done
