### ISSUE TITLE
Trouble saving sketch image after generation

### ISSUE THREAD

**Issue by Pickles726** [jordenyt/stable_diffusion_sketch#17]
I am using a Google Pixel Pro 7. When I do a sketch and attempt to save the output from SD, it idles on 'working.'

Using standard txt2img generation saves as expected.

Possibly related, but if I've switched out of the app and left it in the background for a time, I will get a notification that it keeps crashing.
![Screenshot_20231224-034319](https://github.com/jordenyt/stable_diffusion_sketch/assets/30604149/bed76d42-25d0-42c9-a98e-30d76e7021e7)
![Screenshot_20231224-035017](https://github.com/jordenyt/stable_diffusion_sketch/assets/30604149/ff1c3b6c-2d35-456d-864e-464162107011)

**Comment by jordenyt** [comment]
Thanks for reporting the issue.

I have fixed the bug in the latest release.  Please check it.

**Comment by Pickles726** [comment]
Tested on my end and works like a charm! Thanks a ton and happy holidays! :)
