### ISSUE TITLE
Crashes without proper URL format

### ISSUE THREAD

**Issue by Torloy** [jordenyt/stable_diffusion_sketch#23]
When setting no URL or an URL without http:\\ the app crashes on trying to generate an image.
While I expect it not to work with the URL missing, it shouldn't outright crash.

I'd expect an error message instead of a crash.
Also it should handle IPs be themselves instead of requiring http:\\ in the front.

Another suggestion would be a prompt at first start to enter the URL.

Device: Surface Duo

**Comment by jordenyt** [comment]
I have updated the main branch with this fix, and will be released later.
