### ISSUE TITLE
SDXL Base Model not selectable

### ISSUE THREAD

**Issue by short-circuit** [jordenyt/stable_diffusion_sketch#8]
I can't select the base model for SDXL workflow in the app:
![image](https://github.com/jordenyt/stable_diffusion_sketch/assets/4368769/865437aa-464f-44f5-94f7-120cf437350f)

The Refiner model can be selected without any issues:
![image](https://github.com/jordenyt/stable_diffusion_sketch/assets/4368769/0b69ef32-bc9c-4e18-832d-f85094eb16c0)

Is there a specific naming convention that the base model must have? I have 2 different base models. But even when deleting one, the other one is not recognized from the app.

**Comment by jordenyt** [comment]
Please rename your model file name such that it contains "base".

I have already removed this filterimg criteria in latest commit but not release the APK yet.
