### ISSUE TITLE
Struggling to run the server on the app >>> ERROR 404

### ISSUE THREAD

**Issue by Vittorio792** [jordenyt/stable_diffusion_sketch#9]
Hello there,
I'm sorry if I'll sound dumb but I'm new to this and these are my first trials and errors...
Basically my problem is this, I edited the file **webui-user.bat** in this way:

```
- > @echo off
- > set PYTHON=
- > set GIT=
- > set VENV_DIR=
- > set COMMANDLINE_ARGS= --xformers --api --listen
- > call webui.bat
```

which initialised the server on [**gradio.live**] so that at run time I have a link of something similar to:
[https://d2f6a1adfg65waa734d.gradio.live]
Fact is and I'm probably wrong here that this link if added on the app gives **ERROR 404** meaning there is no connection...
What am I doing wrong? 
I followed the guide meticulously but I'm stuck at this point, is there another way to set up a server? Is it to be done on Cloud only? 
Or is there a way to set up a server locally, if so how?

-- _My goal is to create a server with the pc that I have and use the phone to play with AUTOMATIC11111_--

**Comment by jordenyt** [comment]
Seems connection problem.  Please try to input the "URL" of your server and test it on the web browser of your phone.  If you can connect using your phone's web browser, then it should be working with this app.

**Comment by Vittorio792** [comment]
> 

So, I tried what you suggested and the website functions properly on the phone's browser while on the app it doesn't.

Here is my actions:

> - Stable Diffusion API Server Address: COPY PASTE **functional** address
> - Model Settings: Stable Diffusion model
> - ERROR 404

I forgot to mention in the previous post, in the **webui.py** file I have edited the line mentioned
when you start a local server adding this:
launch(_share=True_)(
Plus my models are as follow:
> - epicrealism_pureEvolutionV5.safetensor
> - v1-5-pruned-emaonly.safetensor

Since you mentioned that some model may create bugs in the app I'm mentioning them although it seems a connection problem, but who knows...

Thanks for the reply

**Comment by jordenyt** [comment]
Seems that the API cannot be used in "gradio.live".  Please try to access by opening a direct connection to your server on your mobile.

**Comment by Vittorio792** [comment]
Can you briefly indicate how?
Thanks

**Comment by jordenyt** [comment]
Open the app and input the network address of your Stable Diffusion server in the "Stable Diffusion Server Address" field.

- If both of your Android device and Server are on the same intranet, you can use the intranet IP, i.e. 192.168.xxx.xxx / 10.xxx.xxx.xxx. You can get this IP by running ipconfig /all on Windows or ifconfig --all on MacOS/Linux.
- If your Android device is on public internet, and your server is on intranet, you need to config your router NAT/Firewall and DDNS. In this case, use the internet IP and translated port number as the server address.
- You can test the server address by using it on Android device's web browser. If it is valid, then you will see automatic1111's webui running on your web browser.

**Comment by Vittorio792** [comment]
Thanks for the reply.
It still does not work though, I'll show the steps I've done.
> - with ipconfig /all on CMD and I got my personal IPv4 192.168.x.x
> - Then inside webui.py where there was 0.0.0.0 I put the IPv4 instead
> - Changed the webui-user.bat into only **set COMMANDLINE_ARGS=--xformers --listen --port xxxx** so that 
> - no gradio.live would start
> - Set up TCP Port Forwarding on a certain port
> - tried both local and public ports


_at this point accessing the website on Android was possible but still error 404 on the app_

At this point I thought it was due to NAT / Firewall or missing DDNS
I went on Router and went on **Static NAT/DMZ**, added my IPv4 so that it became public ( as far as I understand )
> - Then went to my-IP.com, created a new account and created a free Dynamic DNS with my public IP and addeed that on router configuration

 **_still not working_**

I don't know what to do next!
Surely I'm missing something that I do not know

Sorry that I'm bothering you this much, _I'd just like it to work properly_, that's all
